
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.1"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.82
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 20
y = 20

[selection]
save_to_clipboard = true

[general]
live_config_reload = true
import = ["/home/rushdynamic/.config/alacritty/colorschemes/ashes-dark.toml", "/home/rushdynamic/.config/alacritty/fonts.toml"]


[[keyboard.bindings]]
key = "PageUp"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "PageDown"
action = "ScrollLineDown"

[[keyboard.bindings]]
key = "Home"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "PageUp"
mods = "Control|Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Control|Shift"
action = "ScrollPageDown"
