
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.5"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.9
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 20
y = 20

[selection]
save_to_clipboard = true

[general]
live_config_reload = true
import = ["/home/rushdynamic/.config/alacritty/colorschemes/ashes-dark.toml", "/home/rushdynamic/.config/alacritty/fonts.toml"]
