-- Automatically generated by Noctalia. Do not edit.
return {
    active_border = "0xff{{colors.primary.default.hex_stripped}}",
    inactive_border = "0xff{{colors.surface_variant.default.hex_stripped}}"
}